imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  config:
    contentsCss: "EXT:w4_communitynet/Resources/Public/Css/rte.css"
    format_tags: "p;h1;h2;h3;h4;h5;pre"
    justifyClasses:
      - text-left
      - text-center
      - text-end
    stylesSet:
      - { name: "Button", element: "a", attributes: { "class": "btn-u btn-u-filled" } }
      - { name: "Button small", element: "a", attributes: { "class": "btn-u btn-u-small" } }
    extraPlugins:
      - justify
